# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f71d8fd15e5fd72e5ba78e3a12e7100f3b4f89301712588b82507cdcc7d23be0c087e19e2e55c83c5ebeaf108dad76c1e089a38c17df92a3a1abb96ab0fcf4b4

test:
  secret_key_base: 930b2f6fa21f5d28dfa408e737e8910c18b71d42d89d1f01155b9876325c9b02a0b6d2be2f7ebf5b31aaca92b71199831c7ead3bda791d13553506cc0cfb6c41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
