# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

FACEBOOK_APP_ID: 165278117411333
FACEBOOK_APP_SECRET: '10bf4e69a6e57580bcb00c747a5eba35'

GITHUB_KEY: '678eb3356f745b74715a'
GITHUB_SECRET: '0837d89582a5fad5b518dd5cdbbc1a098bc15bd9'
